Pahomov_lab_tasks
shalamot/alg_practice_24 pull request #11
Opened 2024-06-30 12:18 UTC by vRedniy-LumbeRt

Описание в Readme.txt

2024-07-01 23:38 UTC, dart-mih requested changes

2024-07-01 23:38 UTC, dart-mih commented on Readme.txt
Лучше перенести этот файл в папку проекта , а то получается, что для всего репозитория комментарии
И глобально ко всем текстовым файлам и pdf - переведите их md формат, в том числе условия заданий и формулы в Latex обернуть...

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Lab_tasks/Lab_1/Var_1/task_1.pdf
Не совсем понял, почему во втором примере теста используется функция divide(), а не foo(): это просто опечатка или какой-то смысл был заложен?

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Lab_tasks/Lab_1/Var_1/task_2.pdf
Ничего не говорится про ситуацию, когда удаление/дублирование/переворот невозможны:
@
4
ab@
например

Нужно как-то проговорить эту ситуацию в условии

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Lab_tasks/Lab_1/Var_1/task_2.pdf
Из формулировки задания не совсем понятно, откуда студентам брать реализацию стека... Честно говоря, даже я не понял:)
Просто если в тексте прописано, что все это хранить обязательно в стеке, то может показаться, что стек уже реализован - если это так, то его реализацию нужно привести в задании
Если стек не реализован, а его реализация обязательна, то нужно заострить на этом внимание и, возможно, даже попытаться проверить код, распарсив его. 
+ когда будете писать код для проверки работы студента, проверьте, что не было использовано каких-то дополнительных предреализованных стеков и запрет на их использования также нужно прописать текстом 

P.S. Может показаться, что вся эта "душная" возня с формулировками бесполезна... Для 80-90% студентов этого хватит, но неплохо процент людей не против воспользоваться лазейками в формулировках, а иногда и вовсе возникают конфликтные ситуации на этом фоне

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Lab_tasks/Lab_1/Var_1/task_1.pdf
А еще забавно что task_1 имеет внутри номер 2, а task_2 - единицу соответственно:)

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Testing module/Trying_to_understand_the_way_of_parsing_user_tests/for python/Py_check_tests.py
> +        raise Exception('Tests Error: Не пройдены написанные пользователем тесты (проверьте корректность своих тестов).')
Когда будете переделывать проверку под формат мудла - осторожно с исключениями, их лучше отлавливать

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Testing module/Trying_to_understand_the_way_of_parsing_user_tests/for python/Py_check_tests.py
> +                            check_divide(elem)
С таким добротным анализом функций, на самом деле, можно попробовать сделать и проверку общей функциональности - но это уже по желанию вашему

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Testing module/Readme.txt
Глобально насчет модуля с тестами:
Признаюсь честно, я пока не запускал это дело, но идея хорошая. 
 - Единственное что сверху было бы неплохо еще сделать - если студент написал лишние тесты, то не стоит принимать такой ответ, вероятно. 
 - Нужно перенести все эти файлы в мудловский формат работы будет, что повлечет за собой некоторые изменения в коде: вероятно не будет файла с тестами, посколько код студента подается в текстовом формате и не будет такой структуры внутри одной сессии проверки... Если вам нужно поэкспериментировать с чем-то, а пока не создавать финальный тест для студентов, то можете без проблем создавать себе черновик для творчества на мудле (тесты можно удалять и редактировать, только не сотрите лишнего)
 
 P.S. Хотелось бы посмотреть, как это будет работать именно в формате когда код студента подается текстом, а не файлом

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Testing module/Trying_to_understand_the_way_of_parsing_user_tests/for c++/C_check_tests.py
> +clang.cindex.Config.set_library_file("C:\\Users\\stepa\\PycharmProjects\\pythonProject11\\venv\\Lib\\site-packages\\clang\\native\\libclang.dll")  # замените на фактический путь к вашей libclang.dll
Ох не к добру это... Не проверяли, в мудле либа установлена?

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Testing module/Trying_to_understand_the_way_of_parsing_user_tests/for c++/C_check_tests.py
> +    results = analyze_tests(_file_path)
Предлагаю послушать комментарий Константина из другого PR и перейти к классам:
1) не будет вложенных функций
2) можно сделать родительский класс общий и два дочерних под питон и плюсы, что сделает обращение при проверке на разных языках более удобным и читаемым
3) переменные между функциями можно будет просто заносить в поля класса - так удобнее их отслеживать

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Testing module/Trying_to_understand_the_way_of_parsing_user_tests/for c++/C_check_tests.py
> +                test_cases["division_by_zero"] = True
Вынесите подобные константы строчные либо в самое начало файла в переменные, либо где-то в отдельном месте их определите... Они используются многократно и рефакторить будет не очень удобно

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Testing module/Trying_to_understand_the_way_of_parsing_user_tests/for python/Py_check_tests.py
> +    results = analyze_tests(file_path)
Аналогично про классы

2024-07-01 23:38 UTC, dart-mih commented on Pahomov_project/Testing module/Trying_to_understand_the_way_of_parsing_user_tests/for python/Py_check_tests.py
> +        "division_by_zero": False,
И про строчные константы

2024-07-02 12:12 UTC, vRedniy-LumbeRt commented on Pahomov_project/Testing module/Readme.txt
Здравствуйте! Касаемо тестов -- фактически, можно как ограничить, так и дать возможность пользователю тестировать всё, что ему вздумается.

В условиях задач будут просить именно граничные случаи отлавливать, но возможность писать и стандартные тесты, на мой взгляд, стоит оставить --- пользователь будет видеть, что его тест корректен, но явно не покрывает все случаи.

Оставляю итоговый вывод на Ваше усмотрение -- добавить подобную проверку -- дело нескольких минут

2024-07-02 12:15 UTC, vRedniy-LumbeRt commented on Pahomov_project/Testing module/Trying_to_understand_the_way_of_parsing_user_tests/for c++/C_check_tests.py
> +clang.cindex.Config.set_library_file("C:\\Users\\stepa\\PycharmProjects\\pythonProject11\\venv\\Lib\\site-packages\\clang\\native\\libclang.dll")  # замените на фактический путь к вашей libclang.dll
Сегодня обращусь к Константину с просьбой проверить составляемый мною список библиотек (на созвоне было сказано, что сейчас идёт некая настройка, так что добавлять библиотеки хотел сам Константин)

2024-07-02 23:22 UTC, dart-mih requested changes

2024-07-02 23:22 UTC, dart-mih commented on Pahomov_project/Lab_tasks/Lab_1/var_1.md
> +*y = 1 / sqrt(x^2 + 4x + 3)*
Тут описаны примеры, как формулы оформлять https://ashki23.github.io/markdown-latex.html

2024-07-02 23:22 UTC, dart-mih commented on Pahomov_project/Lab_tasks/Lab_1/var_2.md
> +abcde#nu#st
амперсант за решетку заменить надо

2024-07-02 23:22 UTC, dart-mih commented on Pahomov_project/Lab_tasks/Lab_1/var_2.md
> +```python
Рановато рамочку открыли

2024-07-06 23:04 UTC, closed without merging